---
###########################################
# build signed UKI from gentoo-kernel-bin #
###########################################

- name: Build signed UKI from gentoo-kernel-bin
  hosts: gentoo
  gather_facts: yes
  become: yes
  any_errors_fatal: true

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/00-preflight.yml
    - import_tasks: tasks/01-packages.yml
    - import_tasks: tasks/02-secureboot-keys.yml
    - import_tasks: tasks/03-installkernel-hooks.yml
    - import_tasks: tasks/04-sources.yml
    - import_tasks: tasks/05-grub-cleanup.yml
      when: remove_grub | default(false)
